WINDOW_NAME = 'AR'

SCREENSHOT_FILENAME = 'screenshot.png'
SCREENCAST_FILENAME = 'screencast.avi'

KEY_CODE_SPACE = 32
KEY_CODE_TAB = 9
KEY_CODE_ESCAPE = 27

KEY_CODE_0 = 48
KEY_CODE_1 = 49
KEY_CODE_2 = 50
KEY_CODE_3 = 51
KEY_CODE_4 = 52
KEY_CODE_5 = 53
KEY_CODE_6 = 54
